feat/flit support
replit/upm pull request #270
Opened 2024-06-17 22:04 UTC by blast-hardcheese

Why
===

As we continue to expand into the realm of offering better Python package manager support, we're happy to add `flit` to upm.

What changed
============

- Bump `BurntSushi/toml` to 1.4.0
- Broke out `python/poetry.go` and `python/pip.go` to go along with `python/flit.go`
- Fix a bug with pip `requirements.txt` additions where we would take a zero-byte `requirements.txt` and turn it into `\ndep` instead of `dep\n`
- Adding `QuirksCannotAddRemove` to support `flit`, which does not directly support `add` or `remove`. In the future, we can or delete from `pyproject.toml`

Test plan
=========

- Import `https://github.com/mwaskom/seaborn` into Replit
- Run `pip install flit` to get a compatible version of flit
- Run `upm install`
- Verify that dependencies are installed

2024-06-17 22:42 UTC, cdmistman commented on internal/backends/python/python.go
🐐

2024-06-17 22:44 UTC, cdmistman commented on internal/cli/cmds.go
> +		fmt.Println("This backend does not suppport dependency additions")
```suggestion
		fmt.Println("This backend does not suppport dependency addition")
```
nit to keep consistent with the other error message

2024-06-17 22:44 UTC, cdmistman requested changes
integration tests please! lgtm so far though

2024-07-02 18:12 UTC, blast-hardcheese commented
A workaround was found for flit. This work can be brought back if necessary.

2024-07-02 18:12 UTC, closed without merging