Added cache files
replit/upm pull request #86
Opened 2022-09-14 17:51 UTC by airportyh

# Why?

This PR accompanies https://github.com/replit/upm/pull/85

2022-09-26 18:02 UTC, dan-stowell requested changes
What makes a good package mapping? You've told me that the package mapping you created using this code covers all but a few of the most popular 10,000 packages on PyPI. That's great! Can you commit a way to verify that?

If this code produces a good mapping, strictly better than our two-years-out-of-date mapping, I approve this code.

2022-09-28 14:18 UTC, airportyh commented on internal/backends/python/gen_pypi_map/install_diff.go
> +	cmd = exec.Command("sh", "-c", ". "+path+"/bin/activate; python3 /home/toby/upm/internal/backends/python/gen_pypi_map/install_diff.py "+metadata.Info.Name)
Thanks.

2022-09-28 21:42 UTC, airportyh commented
@dan-stowell I have written up a README.md under the `internal/backends/python/regression_tests` folder with how to run the regression tests for yourself. The results I got:

5265 ok
4388 added
346 test errored

2022-09-29 15:33 UTC, airportyh commented
> If this code produces a good mapping, strictly better than our two-years-out-of-date mapping, I approve this code.

@dan-stowell this is ready for you to take a look.

The regression tests take between 17-30 minutes to run, depending on hardware. You can see `internal/backends/python/regression_tests/README.md`. You can also spot check specific packages if you don't want to run the whole thing.

This is the output I got from my run: https://gist.github.com/airportyh/945fb5cf34a60cdcb38a3ce5e48e9274

This is the summary of those results:

```
toby@tobyval:~/upm/internal/backends/python/regression_tests$ cat result27.txt|grep ok|wc
   5265   10530   75416
toby@tobyval:~/upm/internal/backends/python/regression_tests$ cat result27.txt|grep added|wc
   2580    5160   52885
toby@tobyval:~/upm/internal/backends/python/regression_tests$ cat result27.txt|grep no-guess|wc
   1808    3616   53033
toby@tobyval:~/upm/internal/backends/python/regression_tests$ cat result27.txt|grep test-errored|wc
    348     696   11495
```

Possible improvements:
1. I've checked some of the no-guess ones and sometimes info gather in the testing phase isn't returning the correct module. I'll dig deeper into it.
2. For the test-errored ones, that's where we'll need figure out the native dependencies of the module

2022-09-29 15:34 UTC, dan-stowell commented
> @dan-stowell this is ready for you to take a look.

Looking!

2022-09-29 20:10 UTC, merged